typography_spectrum: 0.13897636346518993
color:
  saturation: 0.8891937653534114
  brandStrength: 0.7093041196931154
  lightness: 0.5288254385814071
  brandColors:
    - '#FFFFFF'
    - '#191917'
    - '#296C67'
    - '#64B6AC'
    - '#DA4765'
  rhythmicContrast: 0.25332957901991904
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8293964678887278
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Simon Oitzpw
  email: simon.opitz@luminoso-consulting.de
  url: luminoso-consulting.de
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d10021f9-652c-4314-954b-0d6c5db83590.png
name: uminoso Consultingl
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/50d74ad9-19be-46ed-b7cb-955fdcb544c3.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Shining a light in IT
purpose: []
